name: Deploy to ECS

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/github-oidc-devops-api
          aws-region: us-east-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract Git tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t devops-api .
          docker tag devops-api:latest YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/devops-api:${{ steps.vars.outputs.TAG }}
          docker push YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/devops-api:${{ steps.vars.outputs.TAG }}

      - name: Render task definition with APP_VERSION
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json # Path to your ECS task definition JSON
          container-name: devops-api # Container name in task definition
          image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/devops-api:${{ steps.vars.outputs.TAG }}
          environment-variables: |
            APP_VERSION=${{ steps.vars.outputs.TAG }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: devops-api-service
          cluster: devops-cluster
